server:
  port:
    ${API_PORT:8081}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/music_shop_db}
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:234}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: .html

bonuses:
  max-spend-percent: 30
  accrued-percent: 5
defaultPageSize: 6

api-version:
  "v1"

logging:
  level:
    org.thymeleaf: ERROR
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "my.log"