services:
  postgres:
    image: postgres:15.5
    container_name: ms_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ms_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
  mpa:
    container_name: ms_mpa
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    build: api/mpa
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      DB_URL: "jdbc:postgresql://postgres:${DB_PORT}/${POSTGRES_DB}"
      API_PORT: ${API_PORT}
volumes:
  ms_data:

